name: CI - Build & Test (Docker)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build --pull -t drviki-app:${{ github.sha }} .

      - name: Run container (background)
        run: |
          docker run -d --rm -p 8080:8080 --name drviki-test drviki-app:${{ github.sha }}
          # wait for app to start
          for i in {1..15}; do
            curl -sSf http://localhost:8080/ && break || sleep 2
          done
          echo "Container started and responded."

      - name: Healthcheck endpoint
        run: |
          curl -sSf http://localhost:8080/health | jq .

      - name: Show container logs (if needed)
        if: failure()
        run: docker logs drviki-test || true

      - name: Tear down (always)
        if: always()
        run: docker rm -f drviki-test || true
